"""add hashed password to users

Revision ID: 726b7b6ce669
Revises: 6473a1a69d18
Create Date: 2026-07-30 13:51:51.394771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726b7b6ce669'
down_revision: Union[str, Sequence[str], None] = '6473a1a69d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_token_key'), 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_token_key'), 'users', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
